---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  rubocop:
    enabled: true
    config:
      file: codeclimate_rubocop.yml
ratings:
  paths:
    - "**.rb"
exclude_paths:
  - spec/